config/routes.rb
Rails.application.routes.draw do
   devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio-show'
  get 'angular-items', to: "portfolios#angular"
  
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end
root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	enum status: { draft: 0, published: 1 }
	 extend FriendlyId
  friendly_id :title, use: :slugged
validates_presence_of :title,:body
belongs_to :topic
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies
	accepts_nested_attributes_for :technologies, reject_if:lambda{|attrs| attrs['name'].blank?}

	include Placeholder
	validates_presence_of :title,:body,:main_image,:thumb_image
	def self.angular
		where(sbutitle: 'Angular')
	end
	after_initialize :set_defaults
	def set_defaults
		self.main_image ||= Placeholder.image_generator(height:"600",width:"400")
		self.thumb_image ||= Placeholder.image_generator(height:"350",width:"200")
	end
end

app/models/skill.rb
class Skill < ApplicationRecord
	include Placeholder
	validates_presence_of :title,:percent_utilizes
	after_initialize :set_defaults

	def set_defaults
		self.badge ||= Placeholder.image_generator(height:'250',width: '250')
	end
end

app/models/tech.rb
class Tech < ApplicationRecord
end

app/models/techno.rb
class Techno < ApplicationRecord
	belongs_to :techno

end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :title
	has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable ,:validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include DeviseWhitelist
include SetSource
include DefaultPageContent

	def current_user
		super || OpenStruct.new(name: "Guste Bisht", first_name: "Guste", last_name:"Bisht",email:"test@test.com")	
	end 
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
    @page_title= "My blogs"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'weldone.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    else @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
	extend ActiveSupport::Concern
	included do
		before_action :configure_permitted_parameters, if: :devise_controller?
	end
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
end

app/controllers/concerns/placeholder.rb
module Placeholder
	extend ActiveSupport::Concern
	def self.image_generator(height:,width:)
		"http://placehold.it/#{height}*#{width}"
	end
end

app/controllers/concerns/set_source.rb
module SetSource
	extend ActiveSupport::Concern
	included do
		before_action :set_source
	end


	def set_source
		session[:source] = params[:q] if params[:q]
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@posts=Blog.all
  	@skills=Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"
	def index
		@portfolio_items=Portfolio.all
	end

  def angular
    @angular_portfolio_items=Portfolio.angular
  end


	def new
		@portfolio_items = Portfolio.new
    3.times{ @portfolio_items.technologies.build }
	end

	def create
    @portfolio_items = Portfolio.new( params.require(:portfolio).permit(:title,:subtitle,:body,technologies_attributes: [:name]))

    	respond_to do |format|
	      if @portfolio_items.save
	        format.html { redirect_to portfolios_path, notice: 'weldone.' }
	        
	      else
	        format.html { render :new }
	       end
    	end
  	end

  	def edit
  		@portfolio_items = Portfolio.find(params[:id])
  	end

  	 def update
  	 	respond_to do |format|
  	 	@portfolio_items = Portfolio.find(params[:id])
     	 if @portfolio_items.update(params.require(:portfolio).permit(:title,:subtitle,:body))
			format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
        	else
        	format.html { render :edit }
        	end
   		 end
    end
    def show
    	@portfolio_items=Portfolio.find(params[:id])
    end


    def destroy
    @portfolio_items = Portfolio.find(params[:id])
    @portfolio_items.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      
    end
  end


   
end

app/helpers/application_helper.rb
module ApplicationHelper
	def login_helper
		link_to "login", new_user_session_path 
    	if current_user
      		link_to "Logout", destroy_user_session_path, method: :delete
     	else
      		(link_to "Register", new_user_registration_path)+
      		+"<br>".html_safe+(link_to "login", new_user_session_path) 
    	end 
	end

	def source_helper(layout_name)
		
	 if session[:source]
	 	greeting="Thanks for visiting me from #{session[:source]} and you are on the #{layout_name} layout"
        content_tag(:p,greeting,class:"source_greeting")
     end
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= login_helper %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/nav",location: 'top' %>
    <%= yield %>
    <%= source_helper("application") %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= login_helper %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/nav",location: 'bottom' %>
    <%= yield %>
   <%= source_helper("blog") %>
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= login_helper %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
     <%= render "shared/nav", location: "top" %>
  
    <%= yield %>
    <%= source_helper("application") %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Hi, <%= current_user.first_name if current_user %></h1>
<p>Find me in app/views/pages/home.html.erb</p>
<h1>Blog Posts</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<%= source_helper("application") %>
<%= @skills.inspect %>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
        <div>
          <%= link_to "Home", root_path %>
        </div>
        <div>
          <%= link_to "Portfolio", portfolios_path %>
        </div>
        <div>
          <%= link_to "About Me", about_path %>
        </div>
        <div>
          <%= link_to "Contacts" ,contact_path %>
        </div>
        <div>
          <%= link_to "Blogs", blogs_path %>
        </div>
    </div>